### ISSUE TITLE
Status update

### ISSUE THREAD

**Issue by luvnft** [jiftechnify/nostatus#155]
The status update isn’t clickable.

**Comment by jiftechnify** [comment]
Do you mean this button?
![2024-04-03_18-31](https://github.com/jiftechnify/nostatus/assets/12131273/a8d6c308-bf17-4d9f-b941-4dd416fc699c)

If so, how did you log in?

The button should be disabled if you choose to log in with **public key**, since you can't update status without your secret key or browser extensions.
